### ISSUE TITLE
[ERROR] TypeCastException in Vaadin Application

### ISSUE THREAD

**Issue by JustinVoitel** [microstream-one/examples#24]
Iam trying to integrate Microstream into a vaadin application but after Instantiating the database and running it again I constantly get this error printed:
![image](https://user-images.githubusercontent.com/30449535/102556327-ec7a3180-40c8-11eb-9382-335cda311e8f.png)
My DataRoot object looks like this:
```java
public class DataRoot {

   private String name = "test123";
   private ArrayList<String> names = new ArrayList<>();

   public DataRoot() {
      super();
   }

   public ArrayList<String> getNames() {
      return names;
   }

   public void setNames(ArrayList<String> names) {
      this.names = names;
   }

   @Override
   public String toString() {
      return "Root: " + this.name + ", names size: " + this.names.size();
   }

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }
}
```
But I think this is not the troublemaker. Is it maybe, because the underrlying devserver runs with springboot and it cannot cast back the stored root object ?

## Steps to recreate
1. download example vaadin application from (https://start.vaadin.com/?preset=latest) 
2. copy DataRoot class from above
3. in AboutView.java add:
```java
...
 public AboutView() {
        root = new DataRoot();
        sm = EmbeddedStorage.start(root, Paths.get("/etc/microstream/testapp"));

        System.out.println(root);

        root.setName("newly set name 123");

        sm.storeRoot();
    }
...
```
4. run dev server with:
```bash
mvn spring-boot:run
```
5. navigate to /about
6. stop dev server
7. restart devserver with:
```bash
mvn spring-boot:run
```
Maybe iam doing something wrong or there is still something missing, but help would be appreciated :)

Running on Ubuntu 20.04 using openjdk version "11.0.9.1" 2020-11-04

**Comment by zdenek-jonas** [comment]
In this case, the program runs in the tomcat application server. You need to pass an instance of the tomcat class loader to Microstream.

so instead of:

```
sm = EmbeddedStorage.start(root, Paths.get("/etc/microstream/testapp"));
```


```
sm = EmbeddedStorage.Foundation(Paths.get("/etc/microstream/testapp"))
                .onConnectionFoundation(cf -> cf.setClassLoaderProvider(
                        ClassLoaderProvider.New(Thread.currentThread().getContextClassLoader())
                ))
                .start(root);

```
https://manual.docs.microstream.one/data-store/configuration

**Comment by JustinVoitel** [comment]
Thanks for the fast response 👍It is now working as expected!
